### ISSUE TITLE
bash: script: command not found

### ISSUE THREAD

**Issue by 2745194215** [nodecattel/oreminer#1]
How can this be resolved

Mining operation started. Press cTRLtc to stop.
bash: script: command not found
grep: ore_mine.log: No such file or directoryMining process exited with errorrestarting in 3 seconds...

**Comment by nodecattel** [comment]
thanks for reporting. will look into it soon. The added log logic made the script failed. Will update soon

**Comment by nodecattel** [comment]
try git pull and run again
